language: R
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: A_LONG_ENCRYPTED_STRING

script:
  - ./_build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BOOK_GHP_UPLOAD_KEY
  keep_history: true
  local_dir: build
  on:
    branch: master
